name: ghpages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo sh ./docs/update_gh_pages.sh
        env:
         GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
