name: ghpages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          THE_ANSWER: ${{ secrets.THE_ANSWER }}
          A_TEST: a_test
        run: |
          ls -l ./docs/update_gh_pages.sh
          sudo sh ./docs/update_gh_pages.sh
