name: ghpages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          THE_ANSWER: ${{ secrets.THE_ANSWER }}
          A_TEST: a_test
        run: |
          echo "STARTING..."
          echo ${GITHUB_WORKSPACE}
          echo ${GITHUB_REPOSITORY}
          echo "-------------"
          repo_uri="https://x-access-token:${DEPLOY_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          remote_name="origin"
          main_branch="master"
          target_branch="gh-pages"
          build_dir="${GITHUB_WORKSPACE}/docs"
          cd $GITHUB_WORKSPACE
          ls
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@bots.github.com"
          git checkout "$target_branch"
          git rebase "${remote_name}/${main_branch}"
          cd ./docs
          make html
          cd ..
          echo "MAKE IS DONE"
          git add "$build_dir"
          git commit -m "updated GitHub Pages"
          if [ $? -ne 0 ]; then
              echo "nothing to commit"
              exit 0
          fi
          git remote set-url "$remote_name" "$repo_uri" # includes access token
          git push --force-with-lease "$remote_name" "$target_branch"
          echo "...ENDING"
