name: ghpages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set env
        run: echo ::set-env name=DEPLOY_TOKEN::${{ secrets.DEPLOY_TOKEN }}
      - shell: bash
        run: |
          sudo sh ./docs/update_gh_pages.sh
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
