name: ghpages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build doc
        uses: ammaraskar/sphinx-action@master # build sphinx doc
        with:
          docs-folder: "docs/"
          pre-build-command: "pip install sphinxcontrib.napoleon"
          build-command: "make html"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3 # deploy doc to gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./docs/html
          publish_branch: gh-pages
          allow_empty_commit: true
          keep_files: false
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
