name: ghpages

on:
  push:
    branches:
      - master

jobs:
  env:
    GITHUB_TOKEN: ${{ secrets.github_token }}
    DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
    THE_ANSWER: ${{ secrets.THE_ANSWER }}
    A_TEST: a_test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: building documentation
        run: |
          sudo sh ./docs/update_gh_pages.sh
